### ISSUE TITLE
Several schemas to slonik_build_env

### ISSUE THREAD

**Issue by marco44** [ssinger/slony1-engine#7]

**Comment by marco44** [comment]
Hi,

I'd like to pass several schemas to slonik_build_env. If I provide a patch, would it be interesting ?

**Comment by ssinger** [comment]
If you can do it in a way that doesn't break backward compatibility

**Comment by marco44** [comment]
Hi,

There are two solutions for me:

* either permit passing several -schema options (easy, we are using Getopt::Long, $schema would become an array)
* or passing -schema schema1,schema2… a bit more complicated, as we would have to be careful about schemas containing a colon. But not that much more complicated.

I think #1 is better, but tell me which one you'd rather have (both are quite simple to code anyway).

**Comment by ssinger** [comment]
I prefer #1

**Comment by ssinger** [comment]
Feature added to master

**Comment by ssinger** [comment]
Thanks
